name: "WeebZone: Deploy to Actions"

on:
  push:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: "Checkout WeebZone"
         uses: actions/checkout@main
       
       - name: "Cancel Duplicate Runs"
         uses: styfle/cancel-workflow-action@0.9.0
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: "Initialize WeebZone"
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GIT_NAME }}
           git config --global user.email ${{ secrets.GIT_EMAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
       
       # Cleanup The Actions Workspace Using Custom Composite Run Actions
       - uses: rokibhasansagar/slimhub_actions@main
       
       - name: "Clone Repository"
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} weebzone
       - name: "Running WeebZone"
         timeout-minutes: 345
         continue-on-error: true
         run: |
           cd weebzone
           docker build . -t weebzone
           docker run --env CONFIG_FILE_URL=${{ secrets.CONFIG_FILE_URL }} weebzone
       - name: "Re-Run WeebZone"
         continue-on-error: true
         run: |
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "WeebZone : Re-Run $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.GIT_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:heroku
